import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jamie's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Link href="/"><h1 className="text-3xl text-white font-bold">Jamie&apos;s Blog</h1></Link>
        <p className="text-slate-300">Welcome to my dev blog.</p>
      </div>
    </header>
  )

  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-6 py-6 text-center text-slate-400">
        <p>Developed by Jamie</p>
      </div>
    </footer>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
